### PR TITLE
bestone converted from TAlib to Tulip so it works on Windows

### PR DESCRIPTION
**Pull request by ARGH-Eetu**
also added separate high and low thresholds for RSI

### CODE REVIEW

**Comment by ARGH-Eetu** [comment]
I also inverted the "emashort > emalong" to "emashort < emalong" on the downtrend test on line 124 as it makes more sense to me that way..

**Comment by rafaeldelucena** [comment]
The bestone was taken from here strategyhttps://github.com/askmike/gekko/issues/252, it was probably incomplete.

**Comment by cloggy45** [comment]
@rafaeldelucena Thanks for the heads up.

**Comment by ARGH-Eetu** [comment]
@rafaeldelucena in what way incomplete?
It is missing the functions.js file, but I presume it was just the indicators which are now added to the strategy itself.

The strategy isn't working too well as is, so something may well be amiss :)

**Comment by John1231983** [comment]
Hi everyone, it is very happy to see the implementation. Is the implementation try to reprocucce the result of https://github.com/askmike/gekko/issues/1701#issuecomment-361001834 ?

**Comment by rafaeldelucena** [comment]
@ARGH-Eetu I wrote the talib version which your implementation is based on.

The problem is, this code is the same from the snippet: https://github.com/askmike/gekko/issues/252, only updated to newer gekko version.

The results differ from https://github.com/askmike/gekko/issues/1701, which makes me believe that it's incomplete.

@John1231983 yes it is, but apparently only @wupeng1211 knows how :P

**Comment by renguer0** [comment]
So, there is no bestone for anybody?

Thanks for your sharings.

**Pull request merged**
